uploadPath: /home/ec2-user/0clock/idCards/
firebase: /home/ec2-user/0clock/firebase/clock-9f828-firebase-adminsdk-4n8rl-c21b86c1bb.json
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # 추가
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
server:
  port: 34216