uploadPath: /Users/imsubin/Desktop/0clock
firebase: /Users/imsubin/Desktop/clock-9f828-firebase-adminsdk-4n8rl-c21b86c1bb.json
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/oclock"
    username: oclockManager
    password: oclock123!@#
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
server:
  port: 8080