# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:


#      - uses: ankane/setup-mariadb@v1
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.8.3' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'oclock' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: ${{ secrets.DBUSER }} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DBPASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
#      - name: mysql stop
#        run: sudo systemctl stop mysqld
      - name: mysql start
        run: sudo systemctl start mysqld
      - name: make db
        run: sudo mysql -e "create database if not exists oclock"
      - name: make user
        run: sudo mysql -e ${{ secrets.CREATEDBUSERSQL}}
      - name: grant permission
        run : sudo mysql -e ${{ secrets.GRANTUSERPERMISSON}}
      - uses: actions/checkout@v3
      - name: create dir
        run: sudo mkdir -p ./src/main/resources
      - name: create test dir
        run: sudo mkdir -p ./src/test/resources
      - name: permission 변경
        run: sudo chmod 777 ./src/main/resources
      - name: permission 변경
        run: sudo chmod 777 ./src/test/resources
      - name: fsdf
        run: sudo ls -alR ./src/
      - name: create application.properties
        run: sudo echo -e ${{ secrets.APPLICATIONPROPERTIES}} >> ./src/main/resources/application.properties
      - name: create test application.properties
        run: sudo echo -e ${{ secrets.TESTAPPLICATIONPROPERTIES}} >> ./src/test/resources/application.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: DB init
        run: sudo mysql oclock < ./src/test/resources/schema.sql
#      - name: mysql select
#        run: mysql -u oclockManager -p ${{ secrets.DBPASSWORD}} -e "select * from member;"
      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace